AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0

Description: > 
  Cloudformation per la creazione di una istanza di seed che genera 
  ruolo ed istanza ec2. lancia poi comandi aws per registrare la directory, creare due utenti AD, creare due workspace e ...

Parameters:
  EnvTag:
    Description: Inserisci il tag della struttura
    Type: String
    Default: wksdemo
  KeyName:
    Description: Scegli un keypair esistente
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: scegliere un keypair tra quelli esistenti 
  PublicSubnet0:
    Description: Subnet pubblica 0
    Type: AWS::EC2::Subnet::Id
    Default: subnet-03f7e34317106cf01
  #  Type: String
  PrivateSubnet0:
    Type: String 
    Default: subnet-02fda4c2aecb1f803
  PrivateSubnet1: 
    Type: String 
    Default: subnet-07fe5022217121408
  VPCID:
    Description: VPC Id
    Type: AWS::EC2::VPC::Id
    Default: vpc-011a778985f0e7659
  Directory:
      Type: String 
      Default: d-93671d3e65

  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  
Resources:
# Creazione dell'istanza di seed
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro

      KeyName: !Ref 'KeyName'
      ImageId: !Ref LatestAmiId
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref PublicSubnet0
          GroupSet:
            - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref WKSInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub ${EnvTag}-seed
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
                #!/bin/bash -xe
            - |
              exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            - |
                # Installa il webserver e lo avvia
            - |
                sudo yum install httpd -y
            - |
                sudo service httpd start
            - 'aws --region '
            - !Ref 'AWS::Region' 
            - ' workspaces register-workspace-directory --directory-id ' 
            - !Ref 'Directory'
            - ' '
            - '--subnet-ids '
            - !Ref 'PrivateSubnet0' 
            - ' '
            - !Ref 'PrivateSubnet1'
            - ' '
            - |
               --enable-work-docs
            - 'aws --region eu-west-1 workdocs create-user --organization-id '
            - !Ref Directory  
            - ' --username demo01 --email-address demo01@site.awsapps.com --given-name demo01 --surname icsdemo '
            - |
              --password DemoPassword0
            - |
              sudo curl https://ics-cf-templates.s3-eu-west-1.amazonaws.com/workspacesdemo/wks.json > /home/ec2-user/wks.json
            - 'aws --region '
            - !Ref 'AWS::Region'
            - ' ' 
            - | 
              workspaces create-workspaces --cli-input-json file:///home/ec2-user/wks.json >> wks01.json



      
#Creazione di un security group per l'istanza di seed
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCID
      GroupName: seed-sg
      GroupDescription: abilita SSH da anywhere
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: '0.0.0.0/0'
  
# Creazione del Ruolo e policy 
  WKSRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      RoleName: !Sub ${EnvTag}-role
  WKSPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "workspaces:*",
                "ds:*",
                "iam:PassRole",
                "iam:GetRole",
                "iam:CreateRole",
                "iam:PutRolePolicy",
                "kms:ListAliases",
                "kms:ListKeys",
                "ec2:CreateVpc",
                "ec2:CreateSubnet",
                "ec2:CreateNetworkInterface",
                "ec2:CreateInternetGateway",
                "ec2:CreateRouteTable",
                "ec2:CreateRoute",
                "ec2:CreateTags",
                "ec2:CreateSecurityGroup",
                "ec2:DescribeInternetGateways",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeRouteTables",
                "ec2:DescribeVpcs",
                "ec2:DescribeSubnets",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DescribeAvailabilityZones",
                "ec2:AttachInternetGateway",
                "ec2:AssociateRouteTable",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:DeleteSecurityGroup",
                "ec2:DeleteNetworkInterface",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "workdocs:CreateUser",
                "workdocs:RegisterDirectory",
                "workdocs:DeregisterDirectory",
                "workdocs:AddUserToGroup",
                "workdocs:RemoveUserFromGroup"
              ],
              "Resource": "*"
              }
              ]
             }
      Roles: 
        - !Ref WKSRole
      PolicyName: !Sub ${EnvTag}-pol

  WKSInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref WKSRole


Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  WKSPolicy:
    Description: Policy per workspaces
    Value: !Ref WKSPolicy
  SeedIP:
    Description: Public Ip
    Value: !GetAtt  EC2Instance.PublicIp